ARGS:
 tab: 'cmup'
 eval_dataset: 'cmup'
 GPUS: 0
 model_version: 1
 
 val_batch_size: 4
 nw_eval: 2
 eval: True
 collision_aware_centermap: False
 collision_factor: 0.2
 calc_PVE_error: False

 backbone: 'effnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2
 smpl_mesh_root_align: True

 model_path: trained_models/ROMP_EfficientNetV2S_TPB.pkl
#  dataset_rootdir: '/media/svenbecker/Data_HDD_Linux/dlav/dataset'