
ARGS:
 tab: 'webcam'
 gpu: 0 

 backbone: 'effnet'
 model_precision: 'fp16'
 val_batch_size: 1
#  model_path:   'trained_models/ROMP_ResNet50_V1.pkl'
 model_path: /home/svenbecker/Documents/EPFL/dlav/project/checkpoints/effnet_cm64_V1_effnet_on_gpu0_val_TRAIN_EP5_dot_7/effnet_cm64_V1_effnet_val_cache.pkl
 save_mesh: False
 save_centermap: False
 save_dict_results: False
 smpl_mesh_root_align: False
 save_visualization_on_img: False
 centermap_conf_thresh: 0.25

 make_tracking: True
 temporal_optimization: False
 smooth_coeff: 4.
 show_largest_person_only: False
 visulize_platform: 'integrated' # 'blender' # 
 tracker: 'norfair'
 tracking_target: 'centers' # 'keypoints' #
 add_trans: True
 FOV: 60
 
 webcam: True
 cam_id: 0
 multiprocess: False
 run_on_remote_server: False
 server_ip: 'localhost'
 server_port: 10086
 
 # for picking up sepcific cloth from the wardrobe in model_data, please refer to romp/lib/constants.py
 # 'ghostwhite'/'LightCyan' for using the single color texture.
 mesh_cloth: '009' # 'random' #
 character: 'smpl' # 'nvxia' # 